// Starter Spanish vocabulary list.
// Each entry: { id, en, es, category }
// Keep `en` values unique across the whole list, and `es` values unique
// across the whole list, so a matching pair is never ambiguous.

export const WORDS = [
  // Greetings & common phrases
  { en: 'hello', es: 'hola', category: 'phrases' },
  { en: 'goodbye', es: 'adiós', category: 'phrases' },
  { en: 'please', es: 'por favor', category: 'phrases' },
  { en: 'thank you', es: 'gracias', category: 'phrases' },
  { en: "you're welcome", es: 'de nada', category: 'phrases' },
  { en: 'good morning', es: 'buenos días', category: 'phrases' },
  { en: 'good afternoon', es: 'buenas tardes', category: 'phrases' },
  { en: 'good night', es: 'buenas noches', category: 'phrases' },
  { en: 'how are you', es: 'cómo estás', category: 'phrases' },
  { en: 'excuse me', es: 'perdón', category: 'phrases' },
  { en: 'sorry', es: 'lo siento', category: 'phrases' },
  { en: 'see you later', es: 'hasta luego', category: 'phrases' },
  { en: 'nice to meet you', es: 'mucho gusto', category: 'phrases' },
  { en: 'yes', es: 'sí', category: 'phrases' },
  { en: 'no', es: 'no', category: 'phrases' },

  // Question words
  { en: 'what', es: 'qué', category: 'questions' },
  { en: 'who', es: 'quién', category: 'questions' },
  { en: 'where', es: 'dónde', category: 'questions' },
  { en: 'when', es: 'cuándo', category: 'questions' },
  { en: 'why', es: 'por qué', category: 'questions' },
  { en: 'how', es: 'cómo', category: 'questions' },
  { en: 'how much', es: 'cuánto', category: 'questions' },
  { en: 'which', es: 'cuál', category: 'questions' },

  // Pronouns
  { en: 'I', es: 'yo', category: 'pronouns' },
  { en: 'you (informal)', es: 'tú', category: 'pronouns' },
  { en: 'he', es: 'él', category: 'pronouns' },
  { en: 'she', es: 'ella', category: 'pronouns' },
  { en: 'we', es: 'nosotros', category: 'pronouns' },
  { en: 'they', es: 'ellos', category: 'pronouns' },
  { en: 'my', es: 'mi', category: 'pronouns' },
  { en: 'your', es: 'tu', category: 'pronouns' },

  // Numbers
  { en: 'zero', es: 'cero', category: 'numbers' },
  { en: 'one', es: 'uno', category: 'numbers' },
  { en: 'two', es: 'dos', category: 'numbers' },
  { en: 'three', es: 'tres', category: 'numbers' },
  { en: 'four', es: 'cuatro', category: 'numbers' },
  { en: 'five', es: 'cinco', category: 'numbers' },
  { en: 'six', es: 'seis', category: 'numbers' },
  { en: 'seven', es: 'siete', category: 'numbers' },
  { en: 'eight', es: 'ocho', category: 'numbers' },
  { en: 'nine', es: 'nueve', category: 'numbers' },
  { en: 'ten', es: 'diez', category: 'numbers' },
  { en: 'twenty', es: 'veinte', category: 'numbers' },
  { en: 'thirty', es: 'treinta', category: 'numbers' },
  { en: 'one hundred', es: 'cien', category: 'numbers' },

  // Days of the week
  { en: 'Monday', es: 'lunes', category: 'days' },
  { en: 'Tuesday', es: 'martes', category: 'days' },
  { en: 'Wednesday', es: 'miércoles', category: 'days' },
  { en: 'Thursday', es: 'jueves', category: 'days' },
  { en: 'Friday', es: 'viernes', category: 'days' },
  { en: 'Saturday', es: 'sábado', category: 'days' },
  { en: 'Sunday', es: 'domingo', category: 'days' },

  // Time & weather
  { en: 'today', es: 'hoy', category: 'time' },
  { en: 'tomorrow', es: 'mañana', category: 'time' },
  { en: 'yesterday', es: 'ayer', category: 'time' },
  { en: 'now', es: 'ahora', category: 'time' },
  { en: 'later', es: 'después', category: 'time' },
  { en: 'week', es: 'semana', category: 'time' },
  { en: 'year', es: 'año', category: 'time' },
  { en: 'weather', es: 'el clima', category: 'weather' },
  { en: 'sun', es: 'el sol', category: 'weather' },
  { en: 'rain', es: 'la lluvia', category: 'weather' },
  { en: 'cold', es: 'frío', category: 'weather' },
  { en: 'hot', es: 'caliente', category: 'weather' },

  // Colors
  { en: 'red', es: 'rojo', category: 'colors' },
  { en: 'blue', es: 'azul', category: 'colors' },
  { en: 'green', es: 'verde', category: 'colors' },
  { en: 'yellow', es: 'amarillo', category: 'colors' },
  { en: 'black', es: 'negro', category: 'colors' },
  { en: 'white', es: 'blanco', category: 'colors' },
  { en: 'orange', es: 'naranja', category: 'colors' },
  { en: 'purple', es: 'morado', category: 'colors' },
  { en: 'brown', es: 'marrón', category: 'colors' },
  { en: 'gray', es: 'gris', category: 'colors' },

  // Family
  { en: 'mother', es: 'la madre', category: 'family' },
  { en: 'father', es: 'el padre', category: 'family' },
  { en: 'sister', es: 'la hermana', category: 'family' },
  { en: 'brother', es: 'el hermano', category: 'family' },
  { en: 'son', es: 'el hijo', category: 'family' },
  { en: 'daughter', es: 'la hija', category: 'family' },
  { en: 'grandmother', es: 'la abuela', category: 'family' },
  { en: 'grandfather', es: 'el abuelo', category: 'family' },
  { en: 'friend', es: 'el amigo', category: 'family' },
  { en: 'family', es: 'la familia', category: 'family' },

  // Food & drink
  { en: 'water', es: 'el agua', category: 'food' },
  { en: 'bread', es: 'el pan', category: 'food' },
  { en: 'milk', es: 'la leche', category: 'food' },
  { en: 'coffee', es: 'el café', category: 'food' },
  { en: 'egg', es: 'el huevo', category: 'food' },
  { en: 'cheese', es: 'el queso', category: 'food' },
  { en: 'rice', es: 'el arroz', category: 'food' },
  { en: 'chicken', es: 'el pollo', category: 'food' },
  { en: 'fish', es: 'el pescado', category: 'food' },
  { en: 'fruit', es: 'la fruta', category: 'food' },
  { en: 'apple', es: 'la manzana', category: 'food' },
  { en: 'orange (fruit)', es: 'la naranja', category: 'food' },
  { en: 'vegetable', es: 'la verdura', category: 'food' },
  { en: 'meat', es: 'la carne', category: 'food' },
  { en: 'sugar', es: 'el azúcar', category: 'food' },
  { en: 'salt', es: 'la sal', category: 'food' },
  { en: 'breakfast', es: 'el desayuno', category: 'food' },
  { en: 'lunch', es: 'el almuerzo', category: 'food' },
  { en: 'dinner', es: 'la cena', category: 'food' },
  { en: 'restaurant', es: 'el restaurante', category: 'food' },

  // Common verbs (infinitive)
  { en: 'to be (permanent)', es: 'ser', category: 'verbs' },
  { en: 'to be (state)', es: 'estar', category: 'verbs' },
  { en: 'to have', es: 'tener', category: 'verbs' },
  { en: 'to do/make', es: 'hacer', category: 'verbs' },
  { en: 'to go', es: 'ir', category: 'verbs' },
  { en: 'to want', es: 'querer', category: 'verbs' },
  { en: 'to be able to', es: 'poder', category: 'verbs' },
  { en: 'to say', es: 'decir', category: 'verbs' },
  { en: 'to eat', es: 'comer', category: 'verbs' },
  { en: 'to drink', es: 'beber', category: 'verbs' },
  { en: 'to speak', es: 'hablar', category: 'verbs' },
  { en: 'to see', es: 'ver', category: 'verbs' },
  { en: 'to know (fact)', es: 'saber', category: 'verbs' },
  { en: 'to know (person)', es: 'conocer', category: 'verbs' },
  { en: 'to work', es: 'trabajar', category: 'verbs' },
  { en: 'to study', es: 'estudiar', category: 'verbs' },
  { en: 'to live', es: 'vivir', category: 'verbs' },
  { en: 'to sleep', es: 'dormir', category: 'verbs' },
  { en: 'to walk', es: 'caminar', category: 'verbs' },
  { en: 'to run', es: 'correr', category: 'verbs' },
  { en: 'to read', es: 'leer', category: 'verbs' },
  { en: 'to write', es: 'escribir', category: 'verbs' },
  { en: 'to listen', es: 'escuchar', category: 'verbs' },
  { en: 'to buy', es: 'comprar', category: 'verbs' },
  { en: 'to sell', es: 'vender', category: 'verbs' },
  { en: 'to open', es: 'abrir', category: 'verbs' },
  { en: 'to close', es: 'cerrar', category: 'verbs' },
  { en: 'to arrive', es: 'llegar', category: 'verbs' },
  { en: 'to leave', es: 'salir', category: 'verbs' },
  { en: 'to play', es: 'jugar', category: 'verbs' },

  // Adjectives
  { en: 'big', es: 'grande', category: 'adjectives' },
  { en: 'small', es: 'pequeño', category: 'adjectives' },
  { en: 'good', es: 'bueno', category: 'adjectives' },
  { en: 'bad', es: 'malo', category: 'adjectives' },
  { en: 'happy', es: 'feliz', category: 'adjectives' },
  { en: 'sad', es: 'triste', category: 'adjectives' },
  { en: 'beautiful', es: 'hermoso', category: 'adjectives' },
  { en: 'new', es: 'nuevo', category: 'adjectives' },
  { en: 'old', es: 'viejo', category: 'adjectives' },
  { en: 'fast', es: 'rápido', category: 'adjectives' },
  { en: 'slow', es: 'lento', category: 'adjectives' },
  { en: 'easy', es: 'fácil', category: 'adjectives' },
  { en: 'difficult', es: 'difícil', category: 'adjectives' },
  { en: 'tall', es: 'alto', category: 'adjectives' },
  { en: 'short', es: 'bajo', category: 'adjectives' },
  { en: 'strong', es: 'fuerte', category: 'adjectives' },
  { en: 'tired', es: 'cansado', category: 'adjectives' },
  { en: 'important', es: 'importante', category: 'adjectives' },

  // Places
  { en: 'house', es: 'la casa', category: 'places' },
  { en: 'school', es: 'la escuela', category: 'places' },
  { en: 'city', es: 'la ciudad', category: 'places' },
  { en: 'country', es: 'el país', category: 'places' },
  { en: 'street', es: 'la calle', category: 'places' },
  { en: 'store', es: 'la tienda', category: 'places' },
  { en: 'hospital', es: 'el hospital', category: 'places' },
  { en: 'park', es: 'el parque', category: 'places' },
  { en: 'beach', es: 'la playa', category: 'places' },
  { en: 'airport', es: 'el aeropuerto', category: 'places' },

  // Body parts
  { en: 'head', es: 'la cabeza', category: 'body' },
  { en: 'hand', es: 'la mano', category: 'body' },
  { en: 'eye', es: 'el ojo', category: 'body' },
  { en: 'foot', es: 'el pie', category: 'body' },
  { en: 'heart', es: 'el corazón', category: 'body' },
  { en: 'mouth', es: 'la boca', category: 'body' },

  // Clothing & animals
  { en: 'shirt', es: 'la camisa', category: 'clothing' },
  { en: 'shoes', es: 'los zapatos', category: 'clothing' },
  { en: 'dog', es: 'el perro', category: 'animals' },
  { en: 'cat', es: 'el gato', category: 'animals' },
  { en: 'bird', es: 'el pájaro', category: 'animals' },
  { en: 'horse', es: 'el caballo', category: 'animals' },
].map((w, i) => ({ id: i + 1, ...w }));
